# Generated by Django 3.1.7 on 2021-11-08 17:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('purchase', 'Purchase'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='common.useraccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(check=models.Q(balance__gte=Decimal('0')), name='balance_gte_0'),
        ),
        migrations.AlterIndexTogether(
            name='accountoperation',
            index_together={('account', 'created')},
        ),
    ]
